---
title: "Scoping review of school-based interventions for students with intellectual disability"
author: "Lucija Batinovic"
date: last-modified
format:
  html:
    toc: true
    toc-depth: 2
    code-fold: true
    embed-resources: true
execute:
  echo: true
editor_options: 
  chunk_output_type: console
---


```{r}
#| label: setup

###-----------------------------------------------------------------------------
### Script configuration
###-----------------------------------------------------------------------------

runScreeningChunks <- TRUE;

###-----------------------------------------------------------------------------
### Packages
###-----------------------------------------------------------------------------

if ((!(requireNamespace("metabefor", quietly = TRUE))) ||
      (packageVersion("metabefor") < "0.3")) {
  stop("You need to have at least version 0.3 of the `metabefor` package installed; ",
       "install it with:\n\ninstall.packages('metabefor');");
}

metabefor::checkPkgs(
  "here",               ### For easily access to files using 'relative paths'
  "preregr",            ### For specifying (pre)registrations
  "synthesisr",         ### For plotting
  "ggplot2"             ### For plotting
);

### Potentially update to the development version of some packages
# ufs::quietGitLabUpdate("r-packages/preregr@dev", quiet = FALSE);
# ufs::quietGitLabUpdate("r-packages/rock@dev", quiet = FALSE);
# ufs::quietGitLabUpdate("r-packages/metabefor", quiet = FALSE);
# ufs::quietRemotesInstall("rmetaverse/synthesisr",
#                          func = "install_github", quiet = FALSE);

###-----------------------------------------------------------------------------
### Paths
###-----------------------------------------------------------------------------


###-----------------------------------------------------------------------------
### Settings
###-----------------------------------------------------------------------------

knitr::opts_chunk$set(
  echo = TRUE,
  comment = ""
);

###-----------------------------------------------------------------------------
### Extraction script Google sheets URL
###-----------------------------------------------------------------------------

rxsSpec_googleSheetsURL <-
  paste0("https://docs.google.com/spreadsheets/d/",
         "1Ty38BS7MVXOgC-GJ6zzr7E3rC_vQNOMKe-uCvIuHs3c");

```


```{r}
#| label: read-extraction-script-specification
#| include: false

###-----------------------------------------------------------------------------
### Import rxs specifications
###-----------------------------------------------------------------------------

rxsSpecObject <-
  metabefor::rxs_fromSpecifications(
    rxsSpec_googleSheetsURL,
    outputFile = file.path(
      "extractionScriptTemplate.rxs.Rmd"
    )
  )

```

```{r}
#| label: extraction-script-template
#| results: asis
cat("\n\n<pre><textarea rows='40' cols='124' style='font-family:monospace;font-size:11px;white-space:pre;'>",
    unlist(rxsSpecObject$rxsTemplate),
    "</textarea></pre>\n\n",
    sep="\n");
```
