```{r rxs-setup-chunk-T0D3J1, echo=FALSE, results='hide'}
```

<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
<!--                                                                       -->
<!-- Welcome to the R Extraction Script (.rxs.Rmd file) for this source!   -->
<!--                                                                       -->
<!-- You can now start extracting. If you haven't yet studied the          -->
<!-- extractor instructions, please do so first. If you're all set, good   -->
<!-- luck!                                                                 -->
<!--                                                                       -->
<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->

```{r rxs-extraction-chunk, echo=FALSE}
##############################################################################
############################################ START: uniqueSourceIdentifier ###
##############################################################################
uniqueSourceIdentifier <- 
##############################################################################
### 
### SET UNIQUE SOURCE IDENTIFIER
### 
### A unique identifier used in this systematic review to refer to this
### source
### 
##############################################################################
    
    ""
    
##############################################################################
########################################### VALUE DESCRIPTION AND EXAMPLES ###
##############################################################################
### 
### A unique identifier to use in this systematic review. For sources
### with a DOI, this is the last part of the shortDOI as looked up
### through https://shortdoi.org (the part after the "10/"). For sources
### without a DOI (and so, without a shortDOI), this can be, for example,
### the QURID (Quasi-Unique Record Identifier) that was designated during
### the screening phase or which you can create with
### `metabefor::qurid()`.
### 
### EXAMPLES:
### 
### "g5fj"
### "qurid_7h4pksl6"
### 
##############################################################################
############################################## END: uniqueSourceIdentifier ###
##############################################################################

##############################################################################
############################################### START: extractorIdentifier ###
##############################################################################
extractorIdentifier <- 
##############################################################################
### 
### SPECIFY YOUR EXTRACTOR IDENTIFIER
### 
### An identifier unique to every extractor
### 
##############################################################################
    
    ""
    
##############################################################################
########################################### VALUE DESCRIPTION AND EXAMPLES ###
##############################################################################
### 
### Identifiers can only consist of (lower or uppercase) Latin letters
### [a-zA-Z], Arabic numerals [0-9], and underscores [_], and always have
### to start with a letter.
### 
### EXAMPLES:
### 
### "extractor_1"
### "Alex"
### 
##############################################################################
################################################# END: extractorIdentifier ###
##############################################################################


##############################################################################
##################################################### START: source (ROOT) ###
##############################################################################
rxsObject <- data.tree::Node$new('source');
currentEntity <- rxsObject;
##############################################################################

  ############################################################################
  ######################################################## START: metadata ###
  ############################################################################
  currentEntity <- currentEntity$AddChild('metadata');
  ############################################################################
  ### 
  ### METADATA
  ### 
  ### metadata for the paper
  ### 
  ############################################################################
      
  
    ##########################################################################
    ####################################################### START: country ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('country');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### COUNTRY
    ### 
    ### Country where the data were collected. (See the country code:
    ### https://trade.ec.europa.eu/doclib/docs/2015/may/tradoc_153484.pdf)
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A character vector of the ISO 3166-1 alpha-2 country code(s)
    ### 
    ### EXAMPLES:
    ### 
    ### "NL"
    ### c("NL", "BE")
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (VALUE %in% countryCodeList()));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ######################################################### END: country ###
    ##########################################################################
  
  
    ##########################################################################
    ############################################### START: publicationYear ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('publicationYear');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### YEAR
    ### 
    ### Year (or years) the source was published
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A numeric vector of years, where each year must have exactly
    ### 4 digits.
    ### 
    ### EXAMPLES:
    ### 
    ### 2001
    ### c(2001, 2002)
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (is.numeric(VALUE) && all(nchar(VALUE)==4)));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ################################################# END: publicationYear ###
    ##########################################################################
  
  
    ##########################################################################
    ###################################################### START: language ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('language');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### LANGUAGE
    ### 
    ### If reported, state which language the instructions were given
    ### in. If it’s not explicitly stated, leave as NA
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A single character value
    ### 
    ### EXAMPLES:
    ### 
    ### "example"
    ### "another example"
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (is.character(VALUE) && length(VALUE) == 1));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ######################################################## END: language ###
    ##########################################################################
  
  
    ##########################################################################
    ################################################### START: sourceTitle ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('sourceTitle');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### TITLE
    ### 
    ### The title of this source
    ### 
    ##########################################################################
        
        "Enter name here (mandatory)"
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A single character value that cannot be omitted
    ### 
    ### EXAMPLES:
    ### 
    ### "example"
    ### "another example"
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) && !is.null(VALUE) && (nchar(VALUE) > 0));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ##################################################### END: sourceTitle ###
    ##########################################################################
  
  
    ##########################################################################
    ####################################################### START: peerRev ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('peerRev');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### PEER-REVIEW
    ### 
    ### If the article is published in a peer-review journal, vs
    ### other types of publications (thesis, preprint)
    ### 
    ### 
    ##########################################################################
        
        "Enter name here (mandatory)"
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A single character value that cannot be omitted
    ### 
    ### EXAMPLES:
    ### 
    ### "example"
    ### "another example"
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) && !is.null(VALUE) && (nchar(VALUE) > 0));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ######################################################### END: peerRev ###
    ##########################################################################
  
      
  ############################################################################
  ############################################################################
  currentEntity <- currentEntity$parent;
  ############################################################################
  ########################################################## END: metadata ###
  ############################################################################


  ############################################################################
  ###################################################### START: population ###
  ############################################################################
  currentEntity <- currentEntity$AddChild('population');
  ############################################################################
  ### 
  ### POPULATION
  ### 
  ### this is the container for the samples in the study
  ### 
  ############################################################################
      
  
    ##########################################################################
    ####################################### START: participant (REPEATING) ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('participant__1__');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### PARTICIPANTS
    ### 
    ### If it’s a group design, have each row a different group, name
    ### the intervention group “intervention” and comparison
    ### “control”. If we have multiple intervention or control
    ### groups, add “_identifier”. The identifier should either be
    ### the group name or the name of the intervention. Take the
    ### first word of the intervention/control name.
    ### 
    ### If it’s a single-case design, extract each participant
    ### separately
    ### 
    ### 
    ### Only extract data for IDD in the intervention groups
    ### 
    ##########################################################################
        
        "Enter name here (mandatory)"
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A single character value that cannot be omitted
    ### 
    ### EXAMPLES:
    ### 
    ### "example"
    ### "another example"
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) && !is.null(VALUE) && (nchar(VALUE) > 0));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ######################################### END: participant (REPEATING) ###
    ##########################################################################
  
  
    ##########################################################################
    ######################################### START: diagnosis (REPEATING) ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('diagnosis__1__');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### DIAGNOSIS
    ### 
    ### 
    ### Enter diagnosis as reported in the paper, which means using
    ### outdated terms as well. If none are eligible, choose “Other”
    ### and write in the next column.
    ### 
    ### 
    ### - Intellectual disability
    ### - Cognitive impairment
    ### - Cognitive disability
    ### - Mental retardation
    ### - Learning disability (This is not an exact synonym, as it
    ### can often refer to specific issues like dyslexia, ADHD, etc.,
    ### but it is sometimes used more generally)
    ### - Developmental delay
    ### - Mental impairment
    ### - Intellectual developmental disorder
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A vector of strings where each element has to exactly match
    ### one of the values specified in the "values" column of the
    ### Coding sheet
    ### 
    ### EXAMPLE:
    ### 
    ### c(intellectual disability, cognitive impairment, cognitive disability, mental retardation, learning disability, developmental delay, mental impairment, intellectual developmental disorder)
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || all(VALUE %in% c("intellectual disability", "cognitive impairment", "cognitive disability", "mental retardation", "learning disability", "developmental delay", "mental impairment", "intellectual developmental disorder")));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ########################################### END: diagnosis (REPEATING) ###
    ##########################################################################
  
  
    ##########################################################################
    ########################################## START: iddLevel (REPEATING) ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('iddLevel__1__');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### IDD LEVEL
    ### 
    ### State how severe the reported IDD is, if available. If they
    ### only report IQ, do not assume the level but choose the “not
    ### reported” option. According to DSM-V these categories are:
    ### mild, moderate, severe and profound, but it is possible some
    ### will report different terminology, report how it is stated in
    ### the paper. If other, state it in the column next to it. If
    ### the groups contain multiple levels, choose mix and state
    ### which levels in the other column
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A single character value
    ### 
    ### EXAMPLES:
    ### 
    ### "example"
    ### "another example"
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (is.character(VALUE) && length(VALUE) == 1));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ############################################ END: iddLevel (REPEATING) ###
    ##########################################################################
  
  
    ##########################################################################
    ############################################ START: iddRef (REPEATING) ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('iddRef__1__');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### IDD DIAGNOSIS REFERENCE
    ### 
    ### Based on what did they diagnose IDD, if it’s a diagnostic
    ### manual or just reported that they had a diagnosis
    ### 
    ### DSM-IV, DSM-V, ICD, Not specified,other
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A string that has to exactly match one of the values
    ### specified in the "values" column of the Coding sheet
    ### 
    ### EXAMPLE:
    ### 
    ### c(DSM-IV, DSM-V, ICD, not specified, other)
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (VALUE %in% c("DSM-IV", "DSM-V", "ICD", "not specified", "other")));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ############################################## END: iddRef (REPEATING) ###
    ##########################################################################
  
  
    ##########################################################################
    ########################################### START: iqScore (REPEATING) ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('iqScore__1__');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### IQ SCORE
    ### 
    ### If available, report a numeric IQ score, mean, sd and max
    ### value for groups if available, individual scores for single
    ### case design
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### Any valid whole number
    ### 
    ### EXAMPLES:
    ### 
    ### 30
    ### 8762
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (is.numeric(VALUE) && (VALUE%%1==0) && (length(VALUE) == 1)));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ############################################# END: iqScore (REPEATING) ###
    ##########################################################################
  
  
    ##########################################################################
    ############################################ START: iqMean (REPEATING) ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('iqMean__1__');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### IQ MEAN
    ### 
    ### IQ mean of the group
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### Any valid number
    ### 
    ### EXAMPLES:
    ### 
    ### 2.3
    ### 643.2
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (is.numeric(VALUE) && (length(VALUE) == 1)));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ############################################## END: iqMean (REPEATING) ###
    ##########################################################################
  
  
    ##########################################################################
    ############################################## START: iqSd (REPEATING) ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('iqSd__1__');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### IQ SD
    ### 
    ### IQ standard deviation of the group
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### Any valid number
    ### 
    ### EXAMPLES:
    ### 
    ### 2.3
    ### 643.2
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (is.numeric(VALUE) && (length(VALUE) == 1)));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ################################################ END: iqSd (REPEATING) ###
    ##########################################################################
  
  
    ##########################################################################
    ############################################# START: iqMax (REPEATING) ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('iqMax__1__');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### IQ MAX
    ### 
    ### max IQ in the group
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### Any valid number
    ### 
    ### EXAMPLES:
    ### 
    ### 2.3
    ### 643.2
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (is.numeric(VALUE) && (length(VALUE) == 1)));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ############################################### END: iqMax (REPEATING) ###
    ##########################################################################
  
  
    ##########################################################################
    ############################################ START: iqTest (REPEATING) ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('iqTest__1__');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### IQ TEST
    ### 
    ### State which test was used to derive the IQ score
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A single character value
    ### 
    ### EXAMPLE:
    ### 
    ### Wechsler Intelligence Scales (WAIS, WISC) Stanford–Binet Intelligence Scale Fifth Edition Woodcock–Johnson Test of Cognitive Abilities Kaufman Tests Cognitive Assessment System Differential Ability Scales Reynolds Intellectual Ability Scales
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (is.character(VALUE) && length(VALUE) == 1));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ############################################## END: iqTest (REPEATING) ###
    ##########################################################################
  
  
    ##########################################################################
    ###################################### START: otherMeasure (REPEATING) ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('otherMeasure__1__');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### OTHER MEASUREMENT
    ### 
    ### State if they used other measurements to diagnose IDD, e.g.,
    ### adaptive skill scales
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A single character value
    ### 
    ### EXAMPLE:
    ### 
    ### Vineland Adaptive Skills
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (is.character(VALUE) && length(VALUE) == 1));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ######################################## END: otherMeasure (REPEATING) ###
    ##########################################################################
  
  
    ##########################################################################
    ############################################### START: age (REPEATING) ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('age__1__');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### AGE (AGE MEAN, AGE SD, AGE MIN)
    ### 
    ### Report chronological age of the participants, mean score if
    ### group design, individual if single-case design. Report age in
    ### years.
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### Any valid whole number
    ### 
    ### EXAMPLES:
    ### 
    ### 30
    ### 8762
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (is.numeric(VALUE) && (VALUE%%1==0) && (length(VALUE) == 1)));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ################################################# END: age (REPEATING) ###
    ##########################################################################
  
  
    ##########################################################################
    ########################################### START: ageMean (REPEATING) ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('ageMean__1__');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### AGE MEAN
    ### 
    ### mean age of the group
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### Any valid number
    ### 
    ### EXAMPLES:
    ### 
    ### 2.3
    ### 643.2
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (is.numeric(VALUE) && (length(VALUE) == 1)));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ############################################# END: ageMean (REPEATING) ###
    ##########################################################################
  
  
    ##########################################################################
    ############################################# START: ageSd (REPEATING) ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('ageSd__1__');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### AGE SD
    ### 
    ### standard deviation of the age in the group
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### Any valid number
    ### 
    ### EXAMPLES:
    ### 
    ### 2.3
    ### 643.2
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (is.numeric(VALUE) && (length(VALUE) == 1)));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ############################################### END: ageSd (REPEATING) ###
    ##########################################################################
  
  
    ##########################################################################
    ############################################ START: ageMin (REPEATING) ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('ageMin__1__');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### AGE MINIMUM
    ### 
    ### lowest age in the group
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### Any valid number
    ### 
    ### EXAMPLES:
    ### 
    ### 2.3
    ### 643.2
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (is.numeric(VALUE) && (length(VALUE) == 1)));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ############################################## END: ageMin (REPEATING) ###
    ##########################################################################
  
  
    ##########################################################################
    ############################################# START: grade (REPEATING) ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('grade__1__');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### SCHOOL GRADE
    ### 
    ### Report school grades of participants. If it's for single case
    ### design, add separate grade for each participant. If it's
    ### group, report the grade most students are in. if it's
    ### unclear, leave empty
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### Any valid whole number
    ### 
    ### EXAMPLES:
    ### 
    ### 30
    ### 8762
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (is.numeric(VALUE) && (VALUE%%1==0) && (length(VALUE) == 1)));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ############################################### END: grade (REPEATING) ###
    ##########################################################################
  
  
    ##########################################################################
    ###################################### START: intervention (REPEATING) ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('intervention__1__');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### INTERVENTION
    ### 
    ### Start with a name of the intervention; then enter a short
    ### description of the interventions
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A single character value
    ### 
    ### EXAMPLES:
    ### 
    ### "example"
    ### "another example"
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (is.character(VALUE) && length(VALUE) == 1));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ######################################## END: intervention (REPEATING) ###
    ##########################################################################
  
  
    ##########################################################################
    ############################# START: interventionRationale (REPEATING) ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('interventionRationale__1__');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### INTERVENTION RATIONALE
    ### 
    ### Enter the theoretical framework or rationale for implementing
    ### the intervention. If it's based on a theory, just name the
    ### theory (e.g., self-determination theory). If it's explained
    ### but not based on an established theory, write a one sentence
    ### summary of the rationale.
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A single character value
    ### 
    ### EXAMPLES:
    ### 
    ### "example"
    ### "another example"
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (is.character(VALUE) && length(VALUE) == 1));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ############################### END: interventionRationale (REPEATING) ###
    ##########################################################################
  
  
    ##########################################################################
    ################################################### START: studyDesign ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('studyDesign');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### STUDY DESIGN
    ### 
    ### Choose which study design was used:
    ### Group: Between, Within, Mixed (pretest-postest with control
    ### group)
    ### 
    ### SCD: A-B Design (Pre-Post Design), A-B-A (or A-B-A-B) Design
    ### (Reversal Design),Multiple Baseline Design, Alternating
    ### Treatments Design, Multiple Probe Design, Other (Specify)
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A single character value
    ### 
    ### EXAMPLES:
    ### 
    ### "example"
    ### "another example"
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (is.character(VALUE) && length(VALUE) == 1));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ##################################################### END: studyDesign ###
    ##########################################################################
  
  
    ##########################################################################
    ############################################################# START: N ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('N');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### SAMPLE SIZE
    ### 
    ### Total number of participants in the study. If data from
    ### multiple samples are reported, enter the sum of all sample
    ### sizes. If the sample size is not reported, enter "nr".
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A single character value
    ### 
    ### EXAMPLES:
    ### 
    ### "example"
    ### "another example"
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (is.character(VALUE) && length(VALUE) == 1));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ############################################################### END: N ###
    ##########################################################################
  
  
    ##########################################################################
    ########################################## START: duration (REPEATING) ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('duration__1__');
    ##########################################################################
    ### 
    ### DURATION
    ### 
    ### Duration of the intervention.
    ### 
    ##########################################################################
        
        
    ##########################################################################
    ##########################################################################
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ############################################ END: duration (REPEATING) ###
    ##########################################################################
  
  
    ##########################################################################
    ################################# START: durationIntensity (REPEATING) ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('durationIntensity__1__');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### DURATION INTENSITY
    ### 
    ### Duration of each session (on average, if not the same for all
    ### sessions). If the duration of a session is not reported,
    ### enter "nr".
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A single character value
    ### 
    ### EXAMPLES:
    ### 
    ### "example"
    ### "another example"
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (is.character(VALUE) && length(VALUE) == 1));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ################################### END: durationIntensity (REPEATING) ###
    ##########################################################################
  
  
    ##########################################################################
    ##################################### START: durationUnits (REPEATING) ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('durationUnits__1__');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### DURATION UNITS
    ### 
    ### The unit in which the duration of each session is specified.
    ### If not reported, enter "nr".
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A string that has to exactly match one of the values
    ### specified in the "values" column of the Coding sheet
    ### 
    ### EXAMPLE:
    ### 
    ### c("minute", "hour", "day", "nr")
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (VALUE %in% c("minute", "hour", "day", "nr")));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ####################################### END: durationUnits (REPEATING) ###
    ##########################################################################
  
  
    ##########################################################################
    ##################################### START: durationTotal (REPEATING) ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('durationTotal__1__');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### DURATION TOTAL
    ### 
    ### Total duration of the intervention (i.e. of all sessions,
    ### from beginning to end). If not reported, enter "nr".
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A single character value
    ### 
    ### EXAMPLES:
    ### 
    ### "example"
    ### "another example"
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (is.character(VALUE) && length(VALUE) == 1));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ####################################### END: durationTotal (REPEATING) ###
    ##########################################################################
  
  
    ##########################################################################
    ################################ START: durationTotalUnits (REPEATING) ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('durationTotalUnits__1__');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### DURATION TOTAL UNITS
    ### 
    ### The unit in which the total duration of the intervention is
    ### specified. If not reported, enter "nr".
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A string that has to exactly match one of the values
    ### specified in the "values" column of the Coding sheet
    ### 
    ### EXAMPLE:
    ### 
    ### c("minute", "hour", "day", "week", "month", "year", "nr")
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (VALUE %in% c("minute", "hour", "day", "week", "month", "year", "nr")));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ################################## END: durationTotalUnits (REPEATING) ###
    ##########################################################################
  
  
    ##########################################################################
    ######################################### START: frequency (REPEATING) ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('frequency__1__');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### FREQUENCY
    ### 
    ### The number of sessions during the intervention. If not
    ### reported, enter "nr".
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A single character value
    ### 
    ### EXAMPLES:
    ### 
    ### "example"
    ### "another example"
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (is.character(VALUE) && length(VALUE) == 1));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ########################################### END: frequency (REPEATING) ###
    ##########################################################################
  
  
    ##########################################################################
    ########################################## START: training (REPEATING) ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('training__1__');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### TRAINING
    ### 
    ### Teacher training during or prior the intervention. If not
    ### reported, enter "nr".
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A string that has to exactly match one of the values
    ### specified in the "values" column of the Coding sheet
    ### 
    ### EXAMPLE:
    ### 
    ### c("no", "yes", "nr")
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (VALUE %in% c("no", "yes", "nr")));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ############################################ END: training (REPEATING) ###
    ##########################################################################
  
  
    ##########################################################################
    ######################################## START: instructor (REPEATING) ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('instructor__1__');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### INSTRUCTOR
    ### 
    ### enter who was implementing/delivering the intervention
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A single character value
    ### 
    ### EXAMPLES:
    ### 
    ### "example"
    ### "another example"
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (is.character(VALUE) && length(VALUE) == 1));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ########################################## END: instructor (REPEATING) ###
    ##########################################################################
  
  
    ##########################################################################
    ################################ START: settingInstitution (REPEATING) ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('settingInstitution__1__');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### SETTING
    ### 
    ### State the institution where the intervention was implemented.
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A single character value
    ### 
    ### EXAMPLES:
    ### 
    ### "example"
    ### "another example"
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (is.character(VALUE) && length(VALUE) == 1));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ################################## END: settingInstitution (REPEATING) ###
    ##########################################################################
  
  
    ##########################################################################
    ####################################### START: settingRoom (REPEATING) ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('settingRoom__1__');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### SETTING IN THE INSTITITUTION
    ### 
    ### State the room in the institution where the intervention was
    ### implemented.
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A single character value
    ### 
    ### EXAMPLES:
    ### 
    ### "example"
    ### "another example"
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (is.character(VALUE) && length(VALUE) == 1));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ######################################### END: settingRoom (REPEATING) ###
    ##########################################################################
  
  
    ##########################################################################
    ######################################## START: comparison (REPEATING) ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('comparison__1__');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### COMPARISON
    ### 
    ### State which type of comparison/control was implemented. You
    ### can choose this just for the control group row, as it will be
    ### only used to categorize type of control group.
    ### 
    ### Typically Developing Students:
    ### - Chronological Age Matched: Children without any known
    ### disorders or delays who are the same chronological age as the
    ### children with intellectual disabilities.
    ### - Mental Age Matched: Children without any known disorders or
    ### delays whose mental age (as determined by measures of
    ### cognitive abilities) matches that of the children with
    ### intellectual disabilities.
    ### Wait-list Control Groups:
    ### - Chronological Age Matched: Children with intellectual
    ### disabilities who are waiting to receive the intervention and
    ### are the same chronological age as the intervention group.
    ### - Mental Age Matched: Children with intellectual disabilities
    ### who are waiting to receive the intervention and whose mental
    ### age matches that of the intervention group.
    ### Treatment as Usual (TAU) Control Groups:
    ### - Chronological Age Matched: Children continuing to receive
    ### their standard care or treatment who are the same
    ### chronological age as the intervention group.
    ### - Mental Age Matched: Children continuing to receive their
    ### standard care or treatment whose mental age matches that of
    ### the intervention group.
    ### Different Intervention Groups:
    ### - Chronological Age Matched: Children receiving a different
    ### intervention who are the same chronological age as the
    ### intervention group.
    ### - Mental Age Matched: Children receiving a different
    ### intervention whose mental age matches that of the
    ### intervention group.
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A string that has to exactly match one of the values
    ### specified in the "values" column of the Coding sheet
    ### 
    ### EXAMPLE:
    ### 
    ### c(TDS-CA, TDS-MA, WCG-CA, WCG-MA, TAU-CA, TAU-MA, DI-CA, DI-MA)
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (VALUE %in% c("TDS-CA", "TDS-MA", "WCG-CA", "WCG-MA", "TAU-CA", "TAU-MA", "DI-CA", "DI-MA")));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ########################################## END: comparison (REPEATING) ###
    ##########################################################################
  
  
    ##########################################################################
    ########################################### START: outcome (REPEATING) ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('outcome__1__');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### OUTCOMES
    ### 
    ### List all outcomes, each in separate extraction chunk
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A single character value
    ### 
    ### EXAMPLES:
    ### 
    ### "example"
    ### "another example"
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (is.character(VALUE) && length(VALUE) == 1));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ############################################# END: outcome (REPEATING) ###
    ##########################################################################
  
  
    ##########################################################################
    ########################################## START: category (REPEATING) ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('category__1__');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### CATEGORY
    ### 
    ### Choose appropriate categories:
    ### academic (learning the subjects (math, science, reading,
    ### etc.)),
    ### social (participation in class, communicating, playing,
    ### reducing challenging behaviors),
    ### life (dressing, packing, organizing everyday items),
    ### cognitive (attention, meta-reasoning skills etc),
    ### psychological (well-being, self-esteem, engagement),
    ### other
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A single character value that is used as an identifier and so
    ### is always mandatory and can only contain a-z, A-Z, 0-9, and
    ### underscores, and must start with a letter.
    ### 
    ### EXAMPLES:
    ### 
    ### "example1"
    ### "another_identifier_example"
    ### "finalExample"
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(grepl("[a-zA-Z][a-zA-Z0-9_]*", VALUE));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ############################################ END: category (REPEATING) ###
    ##########################################################################
  
  
    ##########################################################################
    ######################################## START: instrument (REPEATING) ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('instrument__1__');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### MEASUREMENT (INSTRUMENT)
    ### 
    ### enter what type of tests/surveys were used, observational
    ### checklist created for the purpose of this research/WIAT
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A single character value
    ### 
    ### EXAMPLES:
    ### 
    ### "example"
    ### "another example"
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (is.character(VALUE) && length(VALUE) == 1));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ########################################## END: instrument (REPEATING) ###
    ##########################################################################
  
  
    ##########################################################################
    ################################ START: instrumentStandard (REPEATING) ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('instrumentStandard__1__');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### MEASUREMENT STANDARDIZATION (INSTRUMENT)
    ### 
    ### Was the instrument standardized
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A string that has to exactly match one of the values
    ### specified in the "values" column of the Coding sheet
    ### 
    ### EXAMPLE:
    ### 
    ### c(yes, no)
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (VALUE %in% c("yes", "no")));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ################################## END: instrumentStandard (REPEATING) ###
    ##########################################################################
  
  
    ##########################################################################
    ########################################## START: examiner (REPEATING) ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('examiner__1__');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### EXAMINER
    ### 
    ### enter who administered tests and assessed results
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A single character value
    ### 
    ### EXAMPLES:
    ### 
    ### "example"
    ### "another example"
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (is.character(VALUE) && length(VALUE) == 1));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ############################################ END: examiner (REPEATING) ###
    ##########################################################################
  
  
    ##########################################################################
    ###################################################### START: followUp ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('followUp');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### FOLLOW-UP PERIOD
    ### 
    ### When was the follow up conducted - if no follow up, leave
    ### default
    ### 
    ##########################################################################
        
        ""
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A single character value
    ### 
    ### EXAMPLES:
    ### 
    ### "example"
    ### "another example"
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (is.character(VALUE) && length(VALUE) == 1));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ######################################################## END: followUp ###
    ##########################################################################
  
      
  ############################################################################
  ############################################################################
  currentEntity <- currentEntity$parent;
  ############################################################################
  ######################################################## END: population ###
  ############################################################################

    
##############################################################################
####################################################### END: source (ROOT) ###
##############################################################################
class(rxsObject) <- c('rxs', 'rxsObject', class(rxsObject));
rxsObject$rxsMetadata <- list(rxsVersion='0.3.0', moduleId=NULL, id=uniqueSourceIdentifier, extractorId=extractorIdentifier);
##############################################################################
##############################################################################
##############################################################################
```

<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
<!--                                                                       -->
<!-- Well done! You are now done extracting this source. Great job!!!      -->
<!--                                                                       -->
<!-- Now, please knit the R Extraction Script into an HTML file and        -->
<!-- carefully check whether you entered everything correctly, since it    -->
<!-- will cost much less time to correct any errors, now that you still    -->
<!-- have this source in your mind, than later on when you'll have to      -->
<!-- dive into it all over.                                                -->
<!--                                                                       -->
<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->












```{r rxs-template-specification-chunk-nP5Qq9, echo=FALSE, results='hide'}
```

```{r rxs-validation-chunk-EwMZem, results='asis'}
metabefor::heading('Validation results', headingLevel = 1);
metabefor::rxs_validation(
  rxsObject,
  stopOnFailure = FALSE,
  rxsTemplateSpec = rxsTemplateSpec);
cat(paste0('- ', rxsObject$validationLog), sep='\n');
```

```{r rxs-show-extracted-data-chunk-ZFcRiz}
if ((!(exists('parsingMultipleRxsFiles'))) || (!parsingMultipleRxsFiles)) {  metabefor::rxs_partial(rxsObject); }
```

```{r rxs-setup-chunk-T0D3J1, include=FALSE, messages=FALSE}
### First check for (and perhaps install) metabefor
if (!(requireNamespace('metabefor', quietly = TRUE))) {
  install.packages('metabefor', repos='http://cran.rstudio.com');
}

### Settings
knitr::opts_chunk$set(echo = FALSE);     ### Suppress R command printing
knitr::opts_chunk$set(comment = NA);     ### Suppress output prefix
```

---
title: "`r paste0('Rxs for \'', uniqueSourceIdentifier, '\' (', metabefor::knittedFileSansExt(), ')')`"
author: "`r paste0('Extractor: ', extractorIdentifier)`"
date: "`r format(Sys.time(), '%Y-%m-%d at %H:%M:%S %Z (UTC%z)')`"
output:
  html_document:
    embed-resources: true
    toc: false
params:
  rxsVersion: "0.3.0"
  rxsRootName: "source"
  rxsObjectName: "rxsObject"
editor_options:
  chunk_output_type: console
---


<!-- Here, the original Rxs template specification is included. ~~~~~~~~~~~-->

```{r rxs-template-specification-chunk-nP5Qq9, echo=FALSE}

rxsTemplateSpec <- 
  list(entities = structure(list(title = c("Metadata", "Country", 
  "Year", "Language", "Title", "Peer-review", "Population", "Participants", 
  "Diagnosis", "IDD level", "IDD diagnosis reference", "IQ Score", 
  "IQ mean", "IQ SD", "IQ max", "IQ test", "Other measurement", 
  "Age (Age mean, Age SD, Age min)", "Age mean", "Age SD", "Age minimum", 
  "School grade", "Intervention", "Intervention rationale", "Study design", 
  "Sample size", "Duration", "Duration intensity", "Duration units", 
  "Duration total", "Duration total units", "Frequency", "Training", 
  "Instructor", "Setting", "Setting in the instititution", "Comparison", 
  "Outcomes", "Category", "Measurement (instrument)", "Measurement standardization (instrument)", 
  "Examiner", "Follow-up period"), description = c("metadata for the paper", 
  "Country where the data were collected. (See the country code: https://trade.ec.europa.eu/doclib/docs/2015/may/tradoc_153484.pdf)", 
  "Year (or years) the source was published", "If reported, state which language the instructions were given in. If it’s not explicitly stated, leave as NA\n", 
  "The title of this source", "If the article is published in a peer-review journal, vs other types of publications (thesis, preprint)\n\n", 
  "this is the container for the samples in the study", "If it’s a group design, have each row a different group, name the intervention group “intervention” and comparison “control”. If we have multiple intervention or control groups, add “_identifier”. The identifier should either be the group name or the name of the intervention. Take the first word of the intervention/control name.\n\nIf it’s a single-case design, extract each participant separately\n\n\nOnly extract data for IDD in the intervention groups", 
  "\nEnter diagnosis as reported in the paper, which means using outdated terms as well. If none are eligible, choose “Other” and write in the next column.\n\n\n- Intellectual disability\n- Cognitive impairment\n- Cognitive disability\n- Mental retardation \n- Learning disability (This is not an exact synonym, as it can often refer to specific issues like dyslexia, ADHD, etc., but it is sometimes used more generally)\n- Developmental delay\n- Mental impairment\n- Intellectual developmental disorder\n", 
  "State how severe the reported IDD is, if available. If they only report IQ, do not assume the level but choose the “not reported” option. According to DSM-V these categories are: mild, moderate, severe and profound, but it is possible some will report different terminology, report how it is stated in the paper. If other, state it in the column next to it. If the groups contain multiple levels, choose mix and state which levels in the other column", 
  "Based on what did they diagnose IDD, if it’s a diagnostic manual or just reported that they had a diagnosis\n\nDSM-IV, DSM-V, ICD, Not specified,other", 
  "If available, report a numeric IQ score, mean, sd and max value for groups if available, individual scores for single case design", 
  "IQ mean of the group", "IQ standard deviation of the group", 
  "max IQ in the group", "State which test was used to derive the IQ score", 
  "State if they used other measurements to diagnose IDD, e.g., adaptive skill scales", 
  "Report chronological age of the participants, mean score if group design, individual if single-case design. Report age in years.", 
  "mean age of the group", "standard deviation of the age in the group", 
  "lowest age in the group", "Report school grades of participants. If it's for single case design, add separate grade for each participant. If it's group, report the grade most students are in. if it's unclear, leave empty", 
  "Start with a name of the intervention; then enter a short description of the interventions\n", 
  "Enter the theoretical framework or rationale for implementing the intervention. If it's based on a theory, just name the theory (e.g., self-determination theory). If it's explained but not based on an established theory, write a one sentence summary of the rationale.", 
  "Choose which study design was used:\nGroup: Between, Within, Mixed (pretest-postest with control group)\n\nSCD: A-B Design (Pre-Post Design), A-B-A (or A-B-A-B) Design (Reversal Design),Multiple Baseline Design, Alternating Treatments Design, Multiple Probe Design, Other (Specify)", 
  "Total number of participants in the study. If data from multiple samples are reported, enter the sum of all sample sizes. If the sample size is not reported, enter \"nr\".", 
  "Duration of the intervention.", "Duration of each session (on average, if not the same for all sessions). If the duration of a session is not reported, enter \"nr\".", 
  "The unit in which the duration of each session is specified. If not reported, enter \"nr\".", 
  "Total duration of the intervention (i.e. of all sessions, from beginning to end). If not reported, enter \"nr\".", 
  "The unit in which the total duration of the intervention is specified. If not reported, enter \"nr\".", 
  "The number of sessions during the intervention. If not reported, enter \"nr\".", 
  "Teacher training during or prior the intervention. If not reported, enter \"nr\".", 
  "enter who was implementing/delivering the intervention", "State the institution where the intervention was implemented.", 
  "State the room in the institution where the intervention was implemented.", 
  "State which type of comparison/control was implemented. You can choose this just for the control group row, as it will be only used to categorize type of control group.\n\nTypically Developing Students:\n- Chronological Age Matched: Children without any known disorders or delays who are the same chronological age as the children with intellectual disabilities.\n- Mental Age Matched: Children without any known disorders or delays whose mental age (as determined by measures of cognitive abilities) matches that of the children with intellectual disabilities.\nWait-list Control Groups:\n- Chronological Age Matched: Children with intellectual disabilities who are waiting to receive the intervention and are the same chronological age as the intervention group.\n- Mental Age Matched: Children with intellectual disabilities who are waiting to receive the intervention and whose mental age matches that of the intervention group.\nTreatment as Usual (TAU) Control Groups:\n- Chronological Age Matched: Children continuing to receive their standard care or treatment who are the same chronological age as the intervention group.\n- Mental Age Matched: Children continuing to receive their standard care or treatment whose mental age matches that of the intervention group.\nDifferent Intervention Groups:\n- Chronological Age Matched: Children receiving a different intervention who are the same chronological age as the intervention group.\n- Mental Age Matched: Children receiving a different intervention whose mental age matches that of the intervention group.", 
  "List all outcomes, each in separate extraction chunk", "Choose appropriate categories:\nacademic (learning the subjects (math, science, reading, etc.)), \nsocial (participation in class, communicating, playing, \nreducing challenging behaviors), \nlife (dressing, packing, organizing everyday items), \ncognitive (attention, meta-reasoning skills etc), \npsychological (well-being, self-esteem, engagement), \nother\n", 
  "enter what type of tests/surveys were used, observational checklist created for the purpose of this research/WIAT", 
  "Was the instrument standardized", "enter who administered tests and assessed results", 
  "When was the follow up conducted - if no follow up, leave default"
  ), identifier = c("metadata", "country", "publicationYear", "language", 
  "sourceTitle", "peerRev", "population", "participant", "diagnosis", 
  "iddLevel", "iddRef", "iqScore", "iqMean", "iqSd", "iqMax", "iqTest", 
  "otherMeasure", "age", "ageMean", "ageSd", "ageMin", "grade", 
  "intervention", "interventionRationale", "studyDesign", "N", 
  "duration", "durationIntensity", "durationUnits", "durationTotal", 
  "durationTotalUnits", "frequency", "training", "instructor", 
  "settingInstitution", "settingRoom", "comparison", "outcome", 
  "category", "instrument", "instrumentStandard", "examiner", "followUp"
  ), valueTemplate = c(NA, "countrycode", "integer.length4.multi", 
  "string", "string.mandatory", "string.mandatory", NA, "string.mandatory", 
  "categorical.multi", "string", "categorical", "integer", "numeric", 
  "numeric", "numeric", "string", "string", "integer", "numeric", 
  "numeric", "numeric", "integer", "string", "string", "string", 
  "string", NA, "string", "categorical", "string", "categorical", 
  "string", "categorical", "string", "string", "string", "categorical", 
  "string", "string.identifier", "string", "categorical", "string", 
  "string"), validValues = c(NA, NA, NA, NA, NA, "yes || no", NA, 
  NA, "intellectual disability || cognitive impairment || cognitive disability || mental retardation || learning disability || developmental delay || mental impairment || intellectual developmental disorder", 
  NA, "DSM-IV || DSM-V || ICD || not specified || other", NA, NA, 
  NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, "\"minute\" || \"hour\" || \"day\" || \"nr\"", 
  NA, "\"minute\" || \"hour\" || \"day\" || \"week\"|| \"month\" || \"year\" || \"nr\"", 
  NA, "\"no\" || \"yes\" || \"nr\"", NA, NA, NA, "TDS-CA  || TDS-MA  || WCG-CA  || WCG-MA  || TAU-CA  || TAU-MA  || DI-CA  || DI-MA", 
  NA, NA, NA, "yes || no", NA, NA), default = c(NA, NA, NA, NA, 
  NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
  NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
  NA, NA, NA, NA, NA, NA, "\"\""), examples = c(NA, NA, NA, NA, 
  NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, "Wechsler Intelligence Scales (WAIS, WISC)\nStanford–Binet Intelligence Scale Fifth Edition\nWoodcock–Johnson Test of Cognitive Abilities\nKaufman Tests\nCognitive Assessment System\nDifferential Ability Scales\nReynolds Intellectual Ability Scales", 
  "Vineland Adaptive Skills", NA, NA, NA, NA, NA, NA, NA, NA, NA, 
  NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
  NA), parent = c(NA, "metadata", "metadata", "metadata", "metadata", 
  "metadata", NA, "population", "population", "population", "population", 
  "population", "population", "population", "population", "population", 
  "population", "population", "population", "population", "population", 
  "population", "population", "population", "population", "population", 
  "population", "population", "population", "population", "population", 
  "population", "population", "population", "population", "population", 
  "population", "population", "population", "population", "population", 
  "population", "population"), ...9 = c(NA_character_, NA_character_, 
  NA_character_, NA_character_, NA_character_, NA_character_, NA_character_, 
  NA_character_, NA_character_, NA_character_, NA_character_, NA_character_, 
  NA_character_, NA_character_, NA_character_, NA_character_, NA_character_, 
  NA_character_, NA_character_, NA_character_, NA_character_, NA_character_, 
  NA_character_, NA_character_, NA_character_, NA_character_, NA_character_, 
  NA_character_, NA_character_, NA_character_, NA_character_, NA_character_, 
  NA_character_, NA_character_, NA_character_, NA_character_, NA_character_, 
  NA_character_, NA_character_, NA_character_, NA_character_, NA_character_, 
  NA_character_), entityRef = c(NA_character_, NA_character_, NA_character_, 
  NA_character_, NA_character_, NA_character_, NA_character_, NA_character_, 
  NA_character_, NA_character_, NA_character_, NA_character_, NA_character_, 
  NA_character_, NA_character_, NA_character_, NA_character_, NA_character_, 
  NA_character_, NA_character_, NA_character_, NA_character_, NA_character_, 
  NA_character_, NA_character_, NA_character_, NA_character_, NA_character_, 
  NA_character_, NA_character_, NA_character_, NA_character_, NA_character_, 
  NA_character_, NA_character_, NA_character_, NA_character_, NA_character_, 
  NA_character_, NA_character_, NA_character_, NA_character_, NA_character_
  ), fieldRef = c(NA_character_, NA_character_, NA_character_, 
  NA_character_, NA_character_, NA_character_, NA_character_, NA_character_, 
  NA_character_, NA_character_, NA_character_, NA_character_, NA_character_, 
  NA_character_, NA_character_, NA_character_, NA_character_, NA_character_, 
  NA_character_, NA_character_, NA_character_, NA_character_, NA_character_, 
  NA_character_, NA_character_, NA_character_, NA_character_, NA_character_, 
  NA_character_, NA_character_, NA_character_, NA_character_, NA_character_, 
  NA_character_, NA_character_, NA_character_, NA_character_, NA_character_, 
  NA_character_, NA_character_, NA_character_, NA_character_, NA_character_
  ), owner = c(NA_character_, NA_character_, NA_character_, NA_character_, 
  NA_character_, NA_character_, NA_character_, NA_character_, NA_character_, 
  NA_character_, NA_character_, NA_character_, NA_character_, NA_character_, 
  NA_character_, NA_character_, NA_character_, NA_character_, NA_character_, 
  NA_character_, NA_character_, NA_character_, NA_character_, NA_character_, 
  NA_character_, NA_character_, NA_character_, NA_character_, NA_character_, 
  NA_character_, NA_character_, NA_character_, NA_character_, NA_character_, 
  NA_character_, NA_character_, NA_character_, NA_character_, NA_character_, 
  NA_character_, NA_character_, NA_character_, NA_character_), 
      list = c(NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_), collapsing = c(NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_), repeating = c(NA, NA, NA, 
      NA, NA, NA, NA, "TRUE", "TRUE", "TRUE", "TRUE", "TRUE", "TRUE", 
      "TRUE", "TRUE", "TRUE", "TRUE", "TRUE", "TRUE", "TRUE", "TRUE", 
      "TRUE", "TRUE", "TRUE", NA, NA, "TRUE", "TRUE", "TRUE", "TRUE", 
      "TRUE", "TRUE", "TRUE", "TRUE", "TRUE", "TRUE", "TRUE", "TRUE", 
      "TRUE", "TRUE", "TRUE", "TRUE", NA), recurring = c(NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_), recursing = c(NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_), identifying = c(NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_)), row.names = c(NA, -43L), class = "data.frame"), 
      valueTemplates = structure(list(identifier = c("numeric", 
      "numeric.multi", "integer", "integer.multi", "integer.length4.multi", 
      "string", "string.multi", "countrycode", "categorical", "categorical.multi", 
      "generalPresence", "string.mandatory", "string.entityRef.mandatory", 
      "string.entityRef.optional", "string.fieldRef.optional", 
      "matrix.crosstab", "string.identifier"), description = c("Any valid number", 
      "A vector of valid numbers", "Any valid whole number", "A vector of integers (i.e. one or more whole numbers)", 
      "A numeric vector of years, where each year must have exactly 4 digits.", 
      "A single character value", "A character vector (i.e. one or more strings)", 
      "A character vector of the ISO 3166-1 alpha-2 country code(s)", 
      "A string that has to exactly match one of the values specified in the \"values\" column of the Coding sheet", 
      "A vector of strings where each element has to exactly match one of the values specified in the \"values\" column of the Coding sheet", 
      "Whether the thing being coded was present or not.", "A single character value that cannot be omitted", 
      "A string that specifies another entity and which MUST be provided", 
      "A string that specifies another entity (can be missing, i.e. NA)", 
      "A string that specifies another field in another entity (can be missing, i.e. NA).", 
      "A table with frequencies; variable 1 in columns, variable 2 in rows; always work from absence/negative/less (left, top) to presence/positive/more (right, bottom)", 
      "A single character value that is used as an identifier and so is always mandatory and can only contain a-z, A-Z, 0-9, and underscores, and must start with a letter."
      ), validValues = c(NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
      "\"Unknown\" || \"Present\" || \"Absent\"", NA, NA, NA, NA, 
      NA, NA), default = c("NA", "NA", "NA", "NA", "NA", "NA", 
      "\"\"", "NA", "NA", "NA", "NA", "\"Enter name here (mandatory)\"", 
      "\"enter <<entityRef>> here\"", "NA", "NA", "NA", "NA"), 
          examples = c("2.3 || 643.2", "c(23.43, 62) || 52.2 || c(76, 12.56, 42)", 
          "30 || 8762", "c(23, 62) || 52 || c(76, 12, 42)", "2001 || c(2001, 2002)", 
          "\"example\" || \"another example\"", "c(\"first value\", \"second value\")", 
          "\"NL\" || c(\"NL\", \"BE\")", "<<validValues>>", "<<validValues>>", 
          "<<validValues>>", "\"example\" || \"another example\"", 
          "<no example>", "<no example>", "<no example>", "rawTable(10, 5, 15, 10) || rawTable(31, 87, 21, 54, 25, 32, ncol=3)", 
          "\"example1\" || \"another_identifier_example\" || \"finalExample\""
          ), validation = c("all(is.na(VALUE)) || (is.numeric(VALUE) && (length(VALUE) == 1))", 
          "all(is.na(VALUE)) || (is.numeric(VALUE))", "all(is.na(VALUE)) || (is.numeric(VALUE) && (VALUE%%1==0) && (length(VALUE) == 1))", 
          "all(is.na(VALUE)) || (is.numeric(VALUE) && all(VALUE%%1==0))", 
          "all(is.na(VALUE)) || (is.numeric(VALUE) && all(nchar(VALUE)==4))", 
          "all(is.na(VALUE)) || (is.character(VALUE) && length(VALUE) == 1)", 
          "all(is.na(VALUE)) || (is.character(VALUE))", "all(is.na(VALUE)) || (VALUE %in% countryCodeList())", 
          "all(is.na(VALUE)) || (VALUE %in% <<validValues>>)", 
          "all(is.na(VALUE)) || all(VALUE %in% <<validValues>>)", 
          "all(is.na(VALUE)) || (VALUE %in% <<validValues>>)", 
          "all(is.na(VALUE)) && !is.null(VALUE) && (nchar(VALUE) > 0)", 
          "rxs_findEntity(node, \"<<entityRef>>\", VALUE)", "all(is.na(VALUE)) || (!is.na(VALUE) && rxs_findEntity(node, \"<<entityRef>>\", VALUE))", 
          "all(is.na(VALUE)) || (!is.na(VALUE) && rxs_findFieldInEntity(node, \"<<fieldRef>>\", VALUE))", 
          "all(is.na(VALUE)) || (class(VALUE) == \"matrix\")", 
          "grepl(\"[a-zA-Z][a-zA-Z0-9_]*\", VALUE)"), error = c("NAME is not numeric, or contains more than one value.", 
          "NAME is not a numeric vector.", "Error about NAME here.", 
          "Error about NAME here.", "Error about NAME here.", "Error about NAME here.", 
          "Error about NAME here.", "Error about NAME here.", "Error about NAME here.", 
          "Error about NAME here.", "Error about NAME here.", "This string (character value) must be entered.", 
          "Enter a valid reference to another entity - or remove unused entities.", 
          "Error about NAME here.", "Error about NAME here.", "Error about NAME here.", 
          "The identifier provided as NAME contains invalid characters (i.e. something that is not a-z, A-Z, 0-9, or _) or does not start with a letter."
          )), row.names = c(NA, -17L), class = "data.frame"), definitions = structure(list(
          term = "Example Term", definition = "Example definition of the term."), row.names = c(NA, 
      -1L), class = "data.frame"), instructionSheet = structure(list(
          heading = c("Introduction", "More instructions", "Opening Remarks", 
          "Closing Remarks"), description = c("These instructions are for extractors using the minimal rxs example.", 
          "Two evaluators will perform data extraction per study in RMarkdown. We'll evaluate these studies and, if reliability is high, the remaining studies will be coded by a single evaluator. In the event that an evaluator determines a study doesn't meet the inclusion standards, a secondary evaluator must validate the coding to determine the exclusion. All studies will be coded by one evaluator and then confirmed by another.\n\nAll entries should be inputted in lowercase letters. If multiple items need to be extracted for a single chunk, they should each be extracted in a separate chunk. Always create a new chunk instead of just adding it to the existing one so it corresponds to the correct study ID. This is particularly important for participants (if it's a group design, extract one chunk per group, if a single-case design, extract one chunk per participant) and outcomes (extract one chunk per outcome, these presumably do not need to match the participants/groups as they should be same for every, but if necessary then try to match chunk and outcome).\nIf you are unsure about which option to choose, leave a comment on the chunk detailing the extraction and explaining your reasoning for why it doesn’t fit the provided options.\nIf a chunk should contain information but it’s not reported in the study, write NA. If the chunks don’t need to be filled out (e.g., single-case design chunks when you have a group design), you can leave those empty.\nWhen you commence data extraction from a specific study, mark it under your name in the markdown document so the other two evaluators are aware which studies are already being extracted. Each evaluator has their own markdown file in the main data extraction project.", 
          "Welcome to the R Extraction Script (.rxs.Rmd file) for this source!\n\nYou can now start extracting. If you haven't yet studied the extractor instructions, please do so first. If you're all set, good luck!", 
          "Well done! You are now done extracting this source. Great job!!!\r\n\r\nNow, please knit the R Extraction Script into an HTML file and carefully check whether you entered everything correctly, since it will cost much less time to correct any errors, now that you still have this source in your mind, than later on when you'll have to dive into it all over."
          )), row.names = c(NA, -4L), class = "data.frame"), errorOnFailingValidation = FALSE, 
      rxsRootName = "source", yamlMetadata = NULL)

```

